### ISSUE TITLE
File ownership changes after yedit

### ISSUE THREAD

**Issue by Nefilime** [mitre/ansible-role-yedit#4]
I use become: true to modify a file that is owned by another user. After yedit completes, it changes the owner of the file.

```
- name: manage yaml files
  yedit:
    src: /etc/patroni/config.yml
    key: bootstrap.dcs
    value: '{{ bootstrap_dcs }}'
  become: true
``` 

It will be great to have ability to set file ownership or save previous ownership.

In additional. If I use --diff key I didn't see any changes in file.
```
TASK [pg-maintenance : manage yaml files] 
ok: [node2]
ok: [node1]
ok: [node3]
```
